### ISSUE TITLE
Unable to login via (new bug only started 24/6/23)

### ISSUE THREAD

**Issue by pdev77** [Pyhass/Pyhiveapi#66]
**Describe the bug**
Using pyhiveapi with 2FA(SMS) and device registration - all was working fine for a couple of weeks.
Then unable to retrieve information via the tokens.
Having retried the login script which is as simple as this:
```
#!/usr/bin/env python3
import os

from pyhiveapi import Hive, SMS_REQUIRED

session = Hive(
    username=(os.environ['hiveuser']),
    password=(os.environ['hivepass']),
)

login = session.login()

if login.get("ChallengeName") == SMS_REQUIRED:
    code = input("Enter 2FA code: ")
    session.sms2fa(code, login)

session.auth.device_registration('pyhiveapi')
deviceData = session.auth.get_device_data()

print(deviceData) # save this info for next time you login
```
it throws:
```
2023-06-27 17:46:18.269 | ERROR    | pyhiveapi.hive:exception_handler:44 - -> 
Error in /usr/lib/python3.8/json/decoder.py
when running raw_decode function
on line 353 - obj, end = self.scan_once(s, idx) 
with vars None
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyhiveapi/hive.py", line 52, in exception_handler
    traceback.print_exc(tb)
  File "/usr/lib/python3.8/traceback.py", line 163, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/usr/lib/python3.8/traceback.py", line 103, in print_exception
    for line in TracebackException(
  File "/usr/lib/python3.8/traceback.py", line 508, in __init__
    self.stack = StackSummary.extract(
  File "/usr/lib/python3.8/traceback.py", line 340, in extract
    if limit >= 0:
TypeError: '>=' not supported between instances of 'traceback' and 'int'

Original exception was:
Traceback (most recent call last):
  File "./1_deviceregistration.py", line 16, in <module>
    session = Hive(
  File "/usr/local/lib/python3.8/dist-packages/pyhiveapi/hive.py", line 111, in __init__
    super().__init__(username, password, websession)
  File "/usr/local/lib/python3.8/dist-packages/pyhiveapi/session.py", line 60, in __init__
    self.auth = Auth(
  File "/usr/local/lib/python3.8/dist-packages/pyhiveapi/api/hive_auth.py", line 116, in __init__
    self.data = self.api.getLoginInfo()
  File "/usr/local/lib/python3.8/dist-packages/pyhiveapi/api/hive_api.py", line 115, in getLoginInfo
    json_data = json.loads(
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 2 (char 1)
```

**Expected behavior**
The registration step provides:
devicegroupkey & authdevicekey & authdevicepasswd

This is using the latest pyhiveapi - with the session.py modifications as per [ https://github.com/Pyhass/Pyhiveapi/issues/57]( https://github.com/Pyhass/Pyhiveapi/issues/57)

I cant figure out how to enable more verbose debugging - pyhiveapi_error.log contains only the above info

**Comment by andyb2000** [comment]
testing this further, it's not just my home broadband IP block (I work for an ISP so have the ability to test from large subnets) - Testing from other subnets in our ISP range, most seem to give this Forbidden, so it doesn't appear to be something I specifically have done, it seems they're blocking huge UK ranges.

**Comment by andyb2000** [comment]
Further, I have found that if you are logged in/authenticated, you should be fine. If you logout or need to re-auth that is the issue as it's only the sso.hivehome.com address that is carrying out the IP ban/filter. The actual https://my.hivehome.com/dashboard lets you in (I tested this by proxying my connection, authenticated then switched off the proxy. My auth cookies remained working/logged in)
